### ISSUE TITLE
Add another `last_request` that returns the request of specific method and URL

### ISSUE THREAD

**Issue by aereal** [astj/p5-Test-WWW-Stub#9]
# Needs

Such as:

```perl
my $g1 = Test::WWW::Stub->register('http://example.com/g1', sub { ... });
my $g2 = Test::WWW::Stub->register('http://example.com/g2', sub { ... });

# some HTTP requets

my $last_req_g1 = Test::WWW::Stub->last_request_for('POST', 'http://example.com/g1');
isnt $last_req_g1->content, '';
```

# Why?

When we try to write tests with HTTP requests, we (want to) think as:

1. Stub HTTP requests/responses
2. Send HTTP requests
3. Assert sent HTTP requests

The `last_request` makes the order of tests look like natural:

**Comment by astj** [comment]
Thank you for your suggestion and p-r!
